### ISSUE TITLE
128 byte per SPI transaction limit

### ISSUE THREAD

**Issue by jsphpl** [LumenRadio/crmx-timotwo-spi-rdm-responder#1]
The [documentation](https://docs.lumenrad.io/timotwo/dmx-interface/#reading-asc-data-over-spi) states that when reading/writing DMX or ASC frames via SPI, a maximum of 128 consecutive bytes can be read/written in one transaction.

However in the example code in this repository, it seems that up to 255 bytes are read in one transaction.

Does the 128 bytes limit also apply to reading/writing RDM frames?

**Comment by e120guru** [comment]
DMX should only be read in 128 bytes blocks, RDM packets can read larger chunks. The 128 byte limit on DMX is to stay coherent with CRMXchip where the hardware could not support larger transfers on SPI than that.
